name: Auto Green Grass (Random)

on:
  schedule:
    - cron: '0 3 * * *' # 매일 한국 시간 낮 12시 0분에 봇이 작동을 시작합니다.
  workflow_dispatch: # 수동 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Wait Random Time (매일 랜덤하게 기다리기)
      run: |
        # 1초부터 18000초(5시간) 사이의 랜덤한 숫자를 뽑습니다.
        RANDOM_DELAY=$((1 + RANDOM % 18000))
        echo "오늘은 $RANDOM_DELAY 초 후에 출석체크를 합니다."
        # 그 시간만큼 가만히 대기합니다.
        sleep $RANDOM_DELAY
        
    - name: Update README
      run: |
        echo "마지막 출석 체크 시간: $(date)" > README.md
        
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "매일매일 잔디 심기 🌿"
        git push
